name: hyrd
description: Hyrd project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  carousel_slider: ^1.3.0
  flutter_svg: ^0.17.4
  dropdownfield: ^1.0.3
  dropdown_formfield: ^0.1.2
  multi_image_picker: ^4.6.1
  # dio: ^2.1.16
  dio: ^3.0.9
  smooth_star_rating: ^1.0.3
  intl: ^0.16.0
  grouped_buttons: ^1.0.4
  badges: ^1.1.0
  page_transition: "^1.1.5"
  pin_entry_text_field: ^0.1.4
  flutter_form_builder: ^3.7.2
  expandable: 4.1.2
  flutter_pagewise: ^1.2.3
  shared_preferences: ^0.5.7+3
  http: ^0.12.1
  toast: ^0.1.5
  country_code_picker: ^1.2.4
  pin_code_fields: ^2.3.0+3
<<<<<<< HEAD
  url_launcher: ^5.2.5
  # google_maps_flutter: ^0.4.0
  google_maps_flutter: ^0.5.28+1
=======
  url_launcher: ^5.4.10
  google_maps_flutter: ^0.4.0
>>>>>>> a791978db76a7e410995e59a403cb1ecec6ef778
  flutter_webview_plugin: ^0.3.10+1
  flutter_html: ^0.11.1
  # vibrate: ^0.0.4
  flutter_vibrate: ^1.0.0
  splashscreen: ^1.2.0
  share: ^0.6.3+6
  flutter_ringtone_player: ^2.0.0
  photo_view: ^0.9.1
  cached_network_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/LOGO-01.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Hyrd
      fonts:
        - asset: assets/fonts/Hyrd.ttf
    - family: HyrdNewIcons
      fonts:
        - asset: assets/fonts/HyrdNewIcons.ttf

  assets:
    - assets/images/
