name: hyrd
description: Hyrd project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  carousel_slider: ^1.3.0
  flutter_svg: ^0.15.0
  dropdownfield: ^1.0.3
  multi_image_picker: ^4.6.1
  dio: 2.1.16
  smooth_star_rating: ^1.0.3
  intl: ^0.16.0
  grouped_buttons: ^1.0.4
  badges: ^1.1.0
  page_transition: "^1.1.5"
  pin_entry_text_field: ^0.1.4
  flutter_form_builder: ^3.7.2

  shared_preferences: ^0.5.6+2
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-BlackItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Thin.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 200
        - asset: assets/fonts/Gilroy-LightItalic.ttf
          weight: 400
          style: italic

  assets:
    - assets/images/
