/// Flutter icons Hyrd
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Hyrd
///      fonts:
///       - asset: fonts/Hyrd.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Hyrd {
  Hyrd._();

  static const _kFontFam = 'Hyrd';

  static const IconData mobile_data = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData money = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData notification_off =
      IconData(0xe802, fontFamily: _kFontFam);
  static const IconData notification_on =
      IconData(0xe803, fontFamily: _kFontFam);
  static const IconData padlock = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData page = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData plus_circle = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData profile = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData remove = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData report = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData right_arrow = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData settings = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData share = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData speaker = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData star = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData team = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData timetable = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData up_arrow = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData users = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData vibrate = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData alert = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData arrow_up = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData auto_login = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData avatar = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData bell = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData bookmark = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData broom = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData broom2 = IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData calendar1 = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData calendar2 = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData calendar_star = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData camera = IconData(0xe820, fontFamily: _kFontFam);
  static const IconData cancel_circle = IconData(0xe821, fontFamily: _kFontFam);
  static const IconData car_axlecount = IconData(0xe822, fontFamily: _kFontFam);
  static const IconData car_buildyear = IconData(0xe823, fontFamily: _kFontFam);
  static const IconData car_capacity = IconData(0xe824, fontFamily: _kFontFam);
  static const IconData car_class = IconData(0xe825, fontFamily: _kFontFam);
  static const IconData car_color = IconData(0xe826, fontFamily: _kFontFam);
  static const IconData car_country = IconData(0xe827, fontFamily: _kFontFam);
  static const IconData car_drivetrain =
      IconData(0xe828, fontFamily: _kFontFam);
  static const IconData car_fueltype = IconData(0xe829, fontFamily: _kFontFam);
  static const IconData car_height = IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData car_import = IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData car_intent = IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData car_liength = IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData car_login = IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData car_mancount = IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData car_mark = IconData(0xe830, fontFamily: _kFontFam);
  static const IconData car_mass = IconData(0xe831, fontFamily: _kFontFam);
  static const IconData car_mileage = IconData(0xe832, fontFamily: _kFontFam);
  static const IconData car_model = IconData(0xe833, fontFamily: _kFontFam);
  static const IconData car_motorname = IconData(0xe834, fontFamily: _kFontFam);
  static const IconData car_register = IconData(0xe835, fontFamily: _kFontFam);
  static const IconData car_transmission =
      IconData(0xe836, fontFamily: _kFontFam);
  static const IconData car_type = IconData(0xe837, fontFamily: _kFontFam);
  static const IconData car_weight = IconData(0xe838, fontFamily: _kFontFam);
  static const IconData car_wheelposition =
      IconData(0xe839, fontFamily: _kFontFam);
  static const IconData chat = IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData checked = IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData close = IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData cog_hand = IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData dot = IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData down_arrow = IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData download = IconData(0xe840, fontFamily: _kFontFam);
  static const IconData edit = IconData(0xe841, fontFamily: _kFontFam);
  static const IconData file = IconData(0xe842, fontFamily: _kFontFam);
  static const IconData filter = IconData(0xe843, fontFamily: _kFontFam);
  static const IconData floppy_disk = IconData(0xe844, fontFamily: _kFontFam);
  static const IconData followers = IconData(0xe845, fontFamily: _kFontFam);
  static const IconData gallery = IconData(0xe846, fontFamily: _kFontFam);
  static const IconData gasoline_pump = IconData(0xe847, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe848, fontFamily: _kFontFam);
  static const IconData hyrd = IconData(0xe849, fontFamily: _kFontFam);
  static const IconData left_arrow = IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData logout = IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData mail = IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData manual_transmission =
      IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData menu_horizontal =
      IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData menu_vertical = IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData car_buildyear_1 =
      IconData(0xe850, fontFamily: _kFontFam);
  static const IconData car_drivetrain_1 =
      IconData(0xe851, fontFamily: _kFontFam);
  static const IconData car_height_1 = IconData(0xe852, fontFamily: _kFontFam);
  static const IconData car_mileage_1 = IconData(0xe853, fontFamily: _kFontFam);
}
