/// Flutter icons Hyrd
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Hyrd
///      fonts:
///       - asset: fonts/Hyrd.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Hyrd {
  Hyrd._();

  static const _kFontFam = 'Hyrd';

  static const IconData gasoline_pump = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData hyrd = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData left_arrow = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData mail = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData manual_transmission = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData menu_horizontal = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData menu_vertical = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData mobile_data = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData money = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData notification_off = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData notification_on = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData padlock = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData page = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData plus_circle = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData profile = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData remove = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData report = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData right_arrow = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData speaker = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData team = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData timetable = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData up_arrow = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData users = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData vibrate = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData alert = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData arrow_up = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData auto_login = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData avatar = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData bell = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData bookmark = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData broom = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData broom2 = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData calendar1 = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData calendar2 = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData calendar_star = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData cancel_circle = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData checked = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData cog_hand = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData dot = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData down_arrow = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData download = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData file = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData filter = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData floppy_disk = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData followers = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData gallery = const IconData(0xe837, fontFamily: _kFontFam);
}
